#!/bin/bash


if hyprctl clients | grep -q "title: sysinfo"; then
    # Kill the kitty window with this title
    pkill -f "kitty --title sysinfo"
else
    # Launch a kitty window that stays open after running both commands
    kitty --title sysinfo -e sh -c 'fastfetch; read -rsn1'
fi
